credentials:
  usernames:
    admin:
      email: admin@isbisportclub.com
      name: Admin
      password: $2b$12$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36WQoeG6Lruj3vjPGga31lW  # mdp: admin123
cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
preauthorized:
  emails:
    - melsbyer@example.com
