[theme]
base = "light"
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[server]
port = 8501
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 200

[browser]
serverAddress = "localhost"

[runner]
fastRerun = true

[client]
showErrorDetails = true

[mapbox]
token = ""

global.developmentMode = false

[deprecation]
showfileUploaderEncoding = false
